# Jekyll
exclude: README.md, manifest.yml, rakefile.rb, Gemfile, Gemfile.lock, update.sh
permalink: /:title
url: http://bgreenacre.github.io/

safe: false
auto: false

future: false
pygments: true
markdown: rdiscount